### ISSUE TITLE
Pushes stared to fail from appveyor

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/Nightly#1]
The pushes to this repository started to fail recently and github says we are over some quota. Would it make sense to trim some of the last three years of history to free some space? @frankmorgner what do you think?
```
+ git push --quiet --set-upstream origin 2022-08-15_e3f5156c
remote: error: this repository is above its size quota        
To https://github.com/OpenSC/Nightly.git
 ! [remote rejected] 2022-08-15_e3f5156c -> 2022-08-15_e3f5156c (pre-receive hook declined)
error: failed to push some refs to 'https://***@github.com/OpenSC/Nightly.git'
```
https://ci.appveyor.com/project/LudovicRousseau/opensc/builds/44470101/job/syqwp01qkft5esg8

**Comment by frankmorgner** [comment]
Last time when this happened, I manually deleted branches that were older than the last release via Github's interface.

**Comment by Jakuje** [comment]
I do not see an option to delete branches anywhere (probably permission issue). Can you delete the old ones or try to grant me the permissions to do that?

**Comment by frankmorgner** [comment]
Can you access this page?
https://github.com/OpenSC/Nightly/branches
If you have the correct access rights, on the right hand side there's a trash button for each of the branches.

**Comment by frankmorgner** [comment]
I've added @OpenSC/opensc-maintainers as "maintainers" to the Nightly repository, I hope this is enough for you to access the branches.

**Comment by Jakuje** [comment]
Thanks. Now, I see the delete buttons on that page, but before, there was just the "new pull request" button.

**Comment by Jakuje** [comment]
Thank you. I went ahead and removed all the branches from 2019 and 2020 so far. I also updated the https://github.com/OpenSC/OpenSC/wiki/OpenSC-Release-Howto to mention this as it would be a good time to do it regularly after the release, instead of waiting 3 years before it will fill up.

**Comment by frankmorgner** [comment]
thank you
